# Generated by Django 3.2.7 on 2021-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('concusion_time', models.IntegerField()),
                ('clocuded', models.BooleanField(default=False)),
            ],
        ),
    ]
