# Generated by Django 3.2.7 on 2021-09-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Pulse',
        ),
    ]
