# Generated by Django 3.2.7 on 2021-09-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulses', '0002_rename_article_pulse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulse',
            old_name='clocuded',
            new_name='cloncuded',
        ),
    ]
