# Generated by Django 3.2.7 on 2021-09-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulses', '0003_rename_clocuded_pulse_cloncuded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulse',
            old_name='cloncuded',
            new_name='concluded',
        ),
    ]
