# Generated by Django 3.2.7 on 2021-09-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulses', '0004_rename_cloncuded_pulse_concluded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulse',
            old_name='concusion_time',
            new_name='conclusion_time',
        ),
    ]
